# yaml-language-server: $schema=https://raw.githubusercontent.com/kjanat/github-labelmanager/v1/.github/labels.schema.json
# GitHub Labels Configuration
# Managed by github-labelmanager
# https://github.com/kjanat/github-labelmanager
---

labels:
  # Issue Types
  - name: bug
    color: "#d73a4a"
    description: Something isn't working as expected

  - name: feature
    color: "#a2eeef"
    description: New feature or enhancement request
    aliases: [enhancement]

  - name: documentation
    color: "#0075ca"
    description: Docs improvements, typos, examples, guides
    aliases: [docs]

  - name: question
    color: "#d876e3"
    description: Clarification needed on behavior or usage

  - name: refactor
    color: "#fbca04"
    description: Code improvements without changing functionality

  # Priority
  - name: "priority: critical"
    color: "#b60205"
    description: Urgent - breaks core functionality or security

  - name: "priority: high"
    color: "#d93f0b"
    description: Important - should be addressed in next release

  - name: "priority: medium"
    color: "#fbca04"
    description: Normal priority - planned for future release

  - name: "priority: low"
    color: "#0e8a16"
    description: Nice to have - backlog item

  # Status
  - name: blocked
    color: "#b60205"
    description: Waiting on external dependency or decision

  - name: "needs review"
    color: "#7057ff"
    description: Ready for code review

  - name: wip
    color: "#fef2c0"
    description: Work in progress, not ready for review

  - name: wontfix
    color: "#ffffff"
    description: Will not be implemented (closed as intended)

  - name: duplicate
    color: "#cfd3d7"
    description: Duplicate of existing issue or PR

  - name: invalid
    color: "#cfd3d7"
    description: Not a valid issue or doesn't apply

  # Components
  - name: "area: cli"
    color: "#1d76db"
    description: Command-line arguments, subcommands, output formats

  - name: "area: tui"
    color: "#1d76db"
    description: Terminal UI, keybindings, widgets, screens

  - name: "area: core"
    color: "#1d76db"
    description: Process filtering, memory tracking, kill logic

  - name: "area: tests"
    color: "#1d76db"
    description: Unit tests, integration tests, test coverage

  - name: "area: ci/cd"
    color: "#1d76db"
    description: GitHub Actions, build pipelines, releases

  - name: "area: rust"
    color: "#1d76db"
    description: Rust code, Cargo dependencies, performance

  - name: "area: python"
    color: "#1d76db"
    description: PyO3 bindings, Python API, type stubs

  - name: "area: pypi"
    color: "#1d76db"
    description: Maturin builds, wheel packaging, PyPI releases

  - name: "area: formatters"
    color: "#1d76db"
    description: Table, JSON, CSV, markdown output formatting

  # Community
  - name: "good first issue"
    color: "#7057ff"
    description: Beginner-friendly - great for first-time contributors

  - name: "help wanted"
    color: "#008672"
    description: Community help needed - extra eyes appreciated

  # Dependencies
  - name: dependencies
    color: "#0366d6"
    description: Cargo.toml or pyproject.toml dependency updates

  - name: security
    color: "#ee0701"
    description: Security vulnerability or hardening

  # Maintenance
  - name: chore
    color: "#fef2c0"
    description: Tooling, configs, housekeeping, version bumps

  - name: performance
    color: "#5319e7"
    description: Speed optimizations, memory reduction, benchmarks

# Labels to delete (if they exist)
delete:
  - enhancement # Renamed to feature via alias
  - docs # Renamed to documentation via alias
