# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
---
language: en-US
tone_instructions: >-
  Be concise, technical, and focus on Rust best practices. Highlight performance
  implications, memory safety, and cross-platform compatibility. Acknowledge good
  patterns briefly.
early_access: true
enable_free_tier: true

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: false
  commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: true
  labeling_instructions:
    # Issue Types
    - label: bug
      instructions: Something isn't working as expected
    - label: feature
      instructions: New feature or enhancement request
    - label: documentation
      instructions: Docs improvements, typos, examples, guides
    - label: question
      instructions: Clarification needed on behavior or usage
    - label: refactor
      instructions: Code improvements without changing functionality
    # Priority
    - label: "priority: critical"
      instructions: Urgent - breaks core functionality or security
    - label: "priority: high"
      instructions: Important - should be addressed in next release
    - label: "priority: medium"
      instructions: Normal priority - planned for future release
    - label: "priority: low"
      instructions: Nice to have - backlog item
    # Status
    - label: blocked
      instructions: Waiting on external dependency or decision
    - label: "needs review"
      instructions: Ready for code review
    - label: wip
      instructions: Work in progress, not ready for review
    - label: wontfix
      instructions: Will not be implemented (closed as intended)
    - label: duplicate
      instructions: Duplicate of existing issue or PR
    - label: invalid
      instructions: Not a valid issue or doesn't apply
    # Components
    - label: "area: cli"
      instructions: Command-line arguments, subcommands, output formats
    - label: "area: tui"
      instructions: Terminal UI, keybindings, widgets, screens
    - label: "area: core"
      instructions: Process filtering, memory tracking, kill logic
    - label: "area: tests"
      instructions: Unit tests, integration tests, test coverage
    - label: "area: ci/cd"
      instructions: GitHub Actions, build pipelines, releases
    - label: "area: rust"
      instructions: Rust code, Cargo dependencies, performance
    - label: "area: python"
      instructions: PyO3 bindings, Python API, type stubs
    - label: "area: pypi"
      instructions: Maturin builds, wheel packaging, PyPI releases
    - label: "area: formatters"
      instructions: Table, JSON, CSV, markdown output formatting
    # Community
    - label: "good first issue"
      instructions: Beginner-friendly - great for first-time contributors
    - label: "help wanted"
      instructions: Community help needed - extra eyes appreciated
    # Dependencies
    - label: dependencies
      instructions: Cargo.toml or pyproject.toml dependency updates
    - label: security
      instructions: Security vulnerability or hardening
    # Maintenance
    - label: chore
      instructions: Tooling, configs, housekeeping, version bumps
    - label: performance
      instructions: Speed optimizations, memory reduction, benchmarks
  suggested_reviewers: true
  auto_assign_reviewers: true
  # Disable decorative features for cleaner reviews
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: true
  abort_on_close: true

  path_filters:
    # Exclude generated/vendored content
    - "!target/**"
    - "!dist/**"
    - "!*.lock"
    - "!Cargo.lock"
    - "!uv.lock"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!docs/cli.md"
    - "!docs/assets/screenshots/**"

  path_instructions:
    - path: "src/**/*.rs"
      instructions: |
        Procclean 3.0 Rust codebase. Focus on:
        - Rust idioms: ownership, borrowing, pattern matching
        - Avoid unnecessary clones/allocations (especially in hot paths)
        - Use iterators over manual loops where appropriate
        - Proper error handling with Result/Option (no unwrap in production)
        - Check for unsafe code that could be safe
        - Performance implications (this is a system utility)
        - Async/await correctness with tokio
        - Platform compatibility (Linux-specific code is OK, document it)

    - path: "src/core/**/*.rs"
      instructions: |
        Core business logic: process filtering, memory tracking, kill operations.
        - Performance critical - suggest optimizations
        - sysinfo API usage correctness
        - All error cases must be handled gracefully
        - No panics in production code paths

    - path: "src/tui/**/*.rs"
      instructions: |
        Ratatui terminal UI code.
        - Proper event loop and state management
        - No blocking operations in render path
        - Keyboard shortcuts must match docs/tui.md
        - Race conditions in background tasks (auto-refresh)
        - Proper cleanup on exit

    - path: "src/cli/**/*.rs"
      instructions: |
        Clap CLI interface.
        - Help text clarity and consistency
        - Subcommand behavior matches docs/cli.md
        - Output format correctness (JSON, CSV, markdown)
        - Error messages are user-friendly

    - path: "src/formatters/**/*.rs"
      instructions: |
        Output formatting for multiple formats.
        - Table rendering correctness
        - JSON serialization (serde)
        - CSV escaping and quoting
        - Markdown table formatting

    - path: "src/python.rs"
      instructions: |
        PyO3 Python bindings.
        - Error conversion Rust -> Python exceptions
        - GIL handling correctness
        - Python API matches python/procclean/__init__.pyi
        - Signature annotations match pyi file
        - Type conversions are correct

    - path: "python/**/*.py"
      instructions: |
        Python wrapper and type stubs.
        - CLI wrapper finds Rust binary (dev vs installed)
        - Type hints complete and accurate
        - Imports work as documented
        - __version__ matches Cargo.toml

    - path: "python/**/*.pyi"
      instructions: |
        Python type stubs for IDE support.
        - Match actual Rust bindings in src/python.rs
        - Complete function signatures
        - Proper type annotations

    - path: "Cargo.toml"
      instructions: |
        Rust dependencies and configuration.
        - Version updates and compatibility
        - Feature flag configuration (python feature)
        - Release profile optimizations
        - Dependency conflicts or duplicates

    - path: "pyproject.toml"
      instructions: |
        Maturin build and PyPI metadata.
        - Version sync with Cargo.toml
        - Python version requirements
        - Maturin configuration correctness
        - Classifiers accuracy

    - path: ".github/workflows/**/*.yml"
      instructions: |
        CI/CD workflows for dual distribution.
        - Rust toolchain setup
        - Cargo caching configuration
        - Maturin wheel builds (multi-platform)
        - Dual publishing: PyPI + Crates.io
        - Security: pinned actions, minimal permissions

    - path: "docs/**/*.md"
      instructions: |
        Documentation for version 3.0.
        - Examples tested and correct
        - Installation instructions work
        - CLI/TUI docs match actual behavior
        - Migration guide from 2.x accurate

    - path: "tests/**/*"
      instructions: |
        Rust unit and integration tests.
        - Test edge cases and error conditions
        - No test code in production paths
        - Proper assertions (not just unwrap)

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    labels:
      - "!wip"
    ignore_title_keywords:
      - WIP
      - DO NOT MERGE

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
    description:
      mode: warning
    issue_assessment:
      mode: warning

  tools:
    # === Rust tools ===
    clippy:
      enabled: true
    # === Python tools (for wrapper) ===
    ruff:
      enabled: true
    # === Shell/YAML/Markdown ===
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    markdownlint:
      enabled: true
    actionlint:
      enabled: true
    # === Security scanning ===
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    checkov:
      enabled: true
    # === General tools ===
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      level: default
    dotenvLint:
      enabled: true
    osvScanner:
      enabled: true
    # === AST pattern matching ===
    ast-grep:
      essential_rules: true
    # === Disabled (not applicable) ===
    biome:
      enabled: false
    hadolint:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    detekt:
      enabled: false
    eslint:
      enabled: false
    fortitudeLint:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    pmd:
      enabled: false
    clang:
      enabled: false
    cppcheck:
      enabled: false
    circleci:
      enabled: false
    sqlfluff:
      enabled: false
    prismaLint:
      enabled: false
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    htmlhint:
      enabled: false
    checkmake:
      enabled: false
    flake8:
      enabled: false
    pylint:
      enabled: false

chat:
  art: false
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/AGENT.md"
      - "**/AGENTS.md"
      - "**/CLAUDE.md"
      - .github/copilot-instructions.md
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto

code_generation:
  docstrings:
    language: en-US
  unit_tests:
    path_instructions:
      - path: "src/**/*.rs"
        instructions: |
          Generate Rust unit tests using #[cfg(test)] modules.
          Test edge cases, error conditions, and boundary values.
          Use assert!, assert_eq!, and Result<(), Box<dyn Error>>.
